### Task 1
'''
Calculate the average age of the employees in the IT firm.
'''

In [35]:
import os
os.getcwd()

'C:\\Users\\meher\\Downloads'

In [23]:
from numpy import genfromtxt
import numpy as np

# Load the CSV file from the current working directory
emp_data = genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv', delimiter=',', skip_header=1)
emp_data

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [24]:
np.genfromtxt('DS1_C4_S1_Employee_Data_Challenge.csv', delimiter=',', skip_header=1) # another alternative

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [25]:
# finsing the avg age of all employees
emp_data[0:50,1]

array([22., 27., 31., 29., 27., 26., 27., 23., 27., 32., 28., 27., 22.,
       27., 35., 33., 28., 22., 25., 27., 37., 27., 24., 27., 28., 26.,
       27., 27., 29., 49., 26., 32., 26., 24., 24., 23., 28., 28., 22.,
       26., 32., 35., 33., 31., 30., 36., 22., 23., 32., 34.])

In [26]:
emp_data[0:50,1].mean() # finding the avg age of all employees, rows 0 up to 50 and column 1

28.26

### Task 2
'''
Display the employee IDs /codes of those employees who are above 25 years of age. Find the count of these employees.
'''

In [27]:
age=emp_data[0:50,1] #printing the age of employees
age

array([22., 27., 31., 29., 27., 26., 27., 23., 27., 32., 28., 27., 22.,
       27., 35., 33., 28., 22., 25., 27., 37., 27., 24., 27., 28., 26.,
       27., 27., 29., 49., 26., 32., 26., 24., 24., 23., 28., 28., 22.,
       26., 32., 35., 33., 31., 30., 36., 22., 23., 32., 34.])

In [28]:
#printing all the ages which are more than 25 years
index=np.where(age>25)
age_more_than_25y=age[index]
age_more_than_25y=age[index]
age_more_than_25y


array([27., 31., 29., 27., 26., 27., 27., 32., 28., 27., 27., 35., 33.,
       28., 27., 37., 27., 27., 28., 26., 27., 27., 29., 49., 26., 32.,
       26., 28., 28., 26., 32., 35., 33., 31., 30., 36., 32., 34.])

In [29]:
print('total number of employees older than 25 years:', age_more_than_25y.size)

total number of employees older than 25 years: 38


In [30]:
index

(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 13, 14, 15, 16, 19, 20, 21,
        23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 36, 37, 39, 40, 41, 42, 43,
        44, 45, 48, 49], dtype=int64),)

In [31]:
print('list of employees whose age is more than 25 years along with their employee codes:',emp_data[index])

list of employees whose age is more than 25 years along with their employee codes: [[ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [37. 28.]
 [38. 28.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [49. 32.]
 [50. 34.]]


### Task 3
''' 
Calculate the total number of employees who are in the age-group of 30—35 years. Display the employee IDs /codes of these employees.
'''


In [32]:
#print all the ages that lie between 30 and 35

indx=np.where((age>30)&(age<35))
print(age[index])

[27. 31. 29. 27. 26. 27. 27. 32. 28. 27. 27. 35. 33. 28. 27. 37. 27. 27.
 28. 26. 27. 27. 29. 49. 26. 32. 26. 28. 28. 26. 32. 35. 33. 31. 30. 36.
 32. 34.]


In [33]:
print('total number of employess whose age lies between 30 and 35 is:', age[index].size)

total number of employess whose age lies between 30 and 35 is: 38


In [34]:
indx

(array([ 2,  9, 15, 31, 40, 42, 43, 48, 49], dtype=int64),)

In [35]:
print('list of employees whose age is more than 30 years but less than 35 years along with their employee codes:',emp_data[indx])

list of employees whose age is more than 30 years but less than 35 years along with their employee codes: [[ 3. 31.]
 [10. 32.]
 [16. 33.]
 [32. 32.]
 [41. 32.]
 [43. 33.]
 [44. 31.]
 [49. 32.]
 [50. 34.]]


In [36]:
import os
os.getcwd()

'C:\\Users\\meher\\Downloads'

In [37]:

from numpy import genfromtxt
import numpy as np


cus_data= genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',', skip_header=1)
cus_data

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

### Task 1
'''
Calculate the average age of the employees in the ITI T firm.
'''

In [38]:
#slicing the specific column containing the spedning score 
spn=cus_data[:,3]
spn

array([39., 81.,  6., 77., 40., 76.,  6., 94.,  3., 72., 14., 99., 15.,
       77., 13., 79., 35., 66., 29., 98., 35., 73.,  5., 73., 14., 82.,
       32., 61., 31., 87.,  4., 73.,  4., 92., 14., 81., 17., 73., 26.,
       75., 35., 92., 36., 61., 28., 65., 55., 47., 42., 42., 52., 60.,
       54., 60., 45., 41., 50., 46., 51., 46., 56., 55., 52., 59., 51.,
       59., 50., 48., 59., 47., 55., 42., 49., 56., 47., 54., 53., 48.,
       52., 42., 51., 55., 41., 44., 57., 46., 58., 55., 60., 46., 55.,
       41., 49., 40., 42., 52., 47., 50., 42., 49., 41., 48., 59., 55.,
       56., 42., 50., 46., 43., 48., 52., 54., 42., 46., 48., 50., 43.,
       59., 43., 57., 56., 40., 58., 91., 29., 77., 35., 95., 11., 75.,
        9., 75., 34., 71.,  5., 88.,  7., 73., 10., 72.,  5., 93., 40.,
       87., 12., 97., 36., 74., 22., 90., 17., 88., 20., 76., 16., 89.,
        1., 78.,  1., 73., 35., 83.,  5., 93., 26., 75., 20., 95., 27.,
       63., 13., 75., 10., 92., 13., 86., 15., 69., 14., 90., 32

In [39]:

# print all the scores which are more than 80
indx=np.where(spn>80) # we are fetching the index position od data items where spend score is >80 
spnscore_more_than_80=spn[indx]
print(spnscore_more_than_80)

[81. 94. 99. 98. 82. 87. 92. 81. 92. 91. 95. 88. 93. 87. 97. 90. 88. 89.
 83. 93. 95. 92. 86. 90. 86. 88. 97. 85. 91. 83.]


In [40]:
print('total number of customers whose spending socre is more than 80:',spnscore_more_than_80.size)

total number of customers whose spending socre is more than 80: 30


### Task 2
'''
Display the employee IDs /codes of those employees who are above 25 years of age. Find the count of these employees.
'''

In [41]:
#printing all the ages of customers
age=cus_data[:,1] #slicing the age column 
age

array([19., 21., 20., 23., 31., 22., 35., 23., 64., 30., 67., 35., 58.,
       24., 37., 22., 35., 20., 52., 35., 35., 25., 46., 31., 54., 29.,
       45., 35., 40., 23., 60., 21., 53., 18., 49., 21., 42., 30., 36.,
       20., 65., 24., 48., 31., 49., 24., 50., 27., 29., 31., 49., 33.,
       31., 59., 50., 47., 51., 69., 27., 53., 70., 19., 67., 54., 63.,
       18., 43., 68., 19., 32., 70., 47., 60., 60., 59., 26., 45., 40.,
       23., 49., 57., 38., 67., 46., 21., 48., 55., 22., 34., 50., 68.,
       18., 48., 40., 32., 24., 47., 27., 48., 20., 23., 49., 67., 26.,
       49., 21., 66., 54., 68., 66., 65., 19., 38., 19., 18., 19., 63.,
       49., 51., 50., 27., 38., 40., 39., 23., 31., 43., 40., 59., 38.,
       47., 39., 25., 31., 20., 29., 44., 32., 19., 35., 57., 32., 28.,
       32., 25., 28., 48., 32., 34., 34., 43., 39., 44., 38., 47., 27.,
       37., 30., 34., 30., 56., 29., 19., 31., 50., 36., 42., 33., 36.,
       32., 40., 28., 36., 36., 52., 30., 58., 27., 59., 35., 37

In [42]:
# print all the ages from 20-24
ind=np.where((age>=20)&(age<25))
print(age[ind])

[21. 20. 23. 22. 23. 24. 22. 20. 23. 21. 21. 20. 24. 24. 23. 21. 22. 24.
 20. 23. 21. 23. 20.]


In [43]:
print('total number of employees whose age lie between 20 and 25 is:',age[ind].size)

total number of employees whose age lie between 20 and 25 is: 23


In [44]:
ind

(array([  1,   2,   3,   5,   7,  13,  15,  17,  29,  31,  35,  39,  41,
         45,  78,  84,  87,  95,  99, 100, 105, 124, 134], dtype=int64),)

In [45]:
#displaying therows pertaiing to only the customer age between 21 and 25
print(cus_data[ind])

[[  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  6.  22.  17.  76.]
 [  8.  23.  18.  94.]
 [ 14.  24.  20.  77.]
 [ 16.  22.  20.  79.]
 [ 18.  20.  21.  66.]
 [ 30.  23.  29.  87.]
 [ 32.  21.  30.  73.]
 [ 36.  21.  33.  81.]
 [ 40.  20.  37.  75.]
 [ 42.  24.  38.  92.]
 [ 46.  24.  39.  65.]
 [ 79.  23.  54.  52.]
 [ 85.  21.  54.  57.]
 [ 88.  22.  57.  55.]
 [ 96.  24.  60.  52.]
 [100.  20.  61.  49.]
 [101.  23.  62.  41.]
 [106.  21.  62.  42.]
 [125.  23.  70.  29.]
 [135.  20.  73.   5.]]


### Task 3
'''
Calculate the total number of employees who are in the age-group of 30—35 years. Display the employee IDs/codes of these employees.
'''


In [52]:
sal=cus_data[:,2] #slicing the salary column
print('the lowest annual salary present in dataset is:',sal.min())

the lowest annual salary present in dataset is: 15.0


In [53]:
#finding the index position of customer whose salary is 15k
index=np.where(sal==15)
print(index)

(array([0, 1], dtype=int64),)


In [56]:
#print the customer id whose annual salary is the lowest 
custid=cus_data[:,0]
print('customerid of customer who has the lowest salary:', custid[index])

customerid of customer who has the lowest salary: [1. 2.]


In [48]:
#finind the highest salary
sal=cu_data[:,2]
print('the highest annual salary present in dataset is:',sal.max())

(array([  4,  23,  43,  49,  51,  52,  69,  88,  94, 125, 133, 137, 141,
        143, 147, 148, 149, 158, 163, 167, 169, 181, 190, 191, 192, 197,
        198], dtype=int64),)

In [58]:
#finding the highest salary
sal=cus_data[:,2]
print('the highest annual salary present in dataset is:',sal.max())

the highest annual salary present in dataset is: 137.0


In [59]:
#fininding the index position of the customer whose salary is 137k usd
index1=np.where(sal==137)
print(index1)

(array([198, 199], dtype=int64),)


In [60]:
#printing the customer id whi highest annual salary 
cusid=cus_data[:,0]
print('customer id with highest annual income:',custid[index1])

customer id with highest annual income: [199. 200.]


### Task 4
'''
Display the details of the customers who are less than 45 years of age, have an annual income greater than $35k, and have a spending score greater than 75. How many such customers are there in the given data?
'''

In [62]:
indx=np.where((spn>75)&(age<45)&(sal>35))
#each of the above individual arrays i.e spend, age and sal which is sliced from original array
print('index position of customers as per the given condition:\n',indx)

index position of customers as per the given condition:
 (array([ 41, 123, 125, 127, 135, 141, 143, 145, 149, 151, 153, 155, 157,
       161, 163, 167, 173, 175, 179, 181, 183, 185, 189, 193, 195, 199],
      dtype=int64),)


In [63]:
print('total number of customers who are eligible for sicount:', age[indx].size)

total number of customers who are eligible for sicount: 26


### Task 5
''' 
During the Christmas season, the company wishes to offer random gift coupons valued between $10 and $50 to all its customers. Add a new column for the gift coupons in the existing data. Display the details of the customers after adding the new column.
'''

In [65]:
#generating random gift coupon between $10 to $50 percent for 200 customers
disc=np.random.randint(10,51, size=(200,1)) #press shift and tab
disc


array([[22],
       [48],
       [23],
       [47],
       [11],
       [22],
       [13],
       [38],
       [22],
       [38],
       [31],
       [21],
       [21],
       [23],
       [29],
       [44],
       [27],
       [17],
       [23],
       [34],
       [16],
       [41],
       [19],
       [47],
       [27],
       [29],
       [28],
       [29],
       [22],
       [35],
       [24],
       [49],
       [14],
       [30],
       [19],
       [33],
       [19],
       [34],
       [30],
       [16],
       [46],
       [19],
       [23],
       [30],
       [18],
       [19],
       [49],
       [46],
       [10],
       [44],
       [30],
       [15],
       [11],
       [46],
       [46],
       [17],
       [19],
       [36],
       [49],
       [42],
       [29],
       [47],
       [33],
       [32],
       [15],
       [10],
       [18],
       [13],
       [14],
       [15],
       [41],
       [39],
       [25],
       [36],
       [17],
       [38],
       [12],